#define PORT_ADDRESS_BUFFER_LENGTH		255
#define MAX_PROTOCOL_UPDATE_DELAY		500 //ms

#define START_ACK_TIMEOUT_MS			2000
#define DATA_TIMEOUT_MS					200
#define DATA_TIMEOUT_MS_FIRST_LOOP		2000
#define DATA_STOP_TIMEOUT				5000
#define DATA_TIMEOUT_MS_PREDICTION		1000

#define READ_BUFFER_SIZE	10

#define NUM_RETRIES_START				3

//data protocol constants
#define CONTROL_BYTE	255
#define DATA_LENGTH		8
#define START_COMMAND	1<<7