#ifndef _RETURN_VALUES
#define _RETURN_VALUES

#define R_SUCCESS				0
#define R_UNKNOWN_FAIL			1
#define R_PORT_DOES_NOT_EXIST	2
#define R_ACCESS_DENIED			3
#define R_ALREADY_OPEN			4
#define R_HANDLE_NOT_OPEN		5

#define R_SERIAL_NOT_OPEN		6
#define R_SERIAL_WRITE_FAILED	7
#define R_START_ACK_TIMEOUT		8
#define R_WRONG_START_ACK		9
#define R_PORT_NOT_KNOWN		10


#endif